# Generated by Django 6.0.4 on 2026-04-10 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodicidad', models.CharField(choices=[('Mensual', 'Mensual'), ('Trimestral', 'Trimestral'), ('Anual', 'Anual'), ('Único', 'Único')], default='Mensual', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Concepto de Pago',
                'verbose_name_plural': 'Conceptos de Pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('anio', models.IntegerField()),
                ('fecha_pago', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Depósito', 'Depósito'), ('Tarjeta', 'Tarjeta')], max_length=20)),
                ('numero_recibo', models.CharField(max_length=20, unique=True)),
                ('comprobante_url', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pagado', 'Pagado'), ('Pendiente', 'Pendiente'), ('Vencido', 'Vencido'), ('Anulado', 'Anulado')], default='Pagado', max_length=20)),
                ('usuario_registro', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pagos', to='core.alumno')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pagos', to='pagos.conceptopago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
                'indexes': [models.Index(fields=['alumno'], name='pagos_pago_alumno__191cb1_idx'), models.Index(fields=['fecha_pago'], name='pagos_pago_fecha_p_af939d_idx'), models.Index(fields=['estado'], name='pagos_pago_estado_c1c831_idx'), models.Index(fields=['anio', 'mes'], name='pagos_pago_anio_17334c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('mes__isnull', False)), fields=('alumno', 'concepto', 'anio', 'mes'), name='unique_pago_mensual', violation_error_message='Este alumno ya tiene un pago registrado para este mes')],
            },
        ),
    ]
