# Generated by Django 6.0.4 on 2026-04-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoderado',
            name='apellidos',
            field=models.CharField(default='Sin Apellidos', max_length=100),
        ),
    ]
