# Generated by Django 6.0.4 on 2026-04-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_apoderado_apellidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoderado',
            name='dni',
            field=models.CharField(default='0000000', max_length=7),
        ),
    ]
