# Generated by Django 6.0.4 on 2026-04-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_apoderado_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoderado',
            name='email',
            field=models.EmailField(default='sin_email@gmail.com', max_length=254),
        ),
    ]
