# Generated by Django 6.0.4 on 2026-04-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_apoderado_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoderado',
            name='dni',
            field=models.CharField(default='00000000', max_length=8),
        ),
    ]
