# Generated by Django 6.0.4 on 2026-04-15 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('fecha_matricula', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Trasladado', 'Trasladado'), ('Retirado', 'Retirado')], default='Activa', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='matriculas', to='core.alumno')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='matriculas', to='core.grado')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='matriculas', to='core.seccion')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['-anio', '-fecha_matricula'],
                'indexes': [models.Index(fields=['anio'], name='matriculas__anio_05cfab_idx'), models.Index(fields=['estado'], name='matriculas__estado_e1f32e_idx')],
                'constraints': [models.UniqueConstraint(fields=('alumno', 'anio'), name='unique_matricula_anio', violation_error_message='El alumno ya está matriculado en este año')],
            },
        ),
    ]
